### PR TITLE
Fixed problem where build was failing locally

### PR DESCRIPTION
**Pull request by geoffreychiou**
Build was failing locally on some machines, this fixes that.

@gomezc please review.

### CODE REVIEW

**Comment by gomezc** [comment]
@geoffreychiou looks like something is breaking - the Travis CI build failed on 125.1 (for Indigo). Otherwise, I agree with the changes in the two files.

**Comment by geoffreychiou** [comment]
> @geoffreychiou looks like something is breaking - the Travis CI build failed on 125.1 (for Indigo). Otherwise, I agree with the changes in the two files.

@gomezc build passed but tests failed. I believe @MauleshSTrivedi is working on getting that fixed in his next pull request. I don't believe the changes in this PR should have any effect on tests passing/failing so i'll leave it up to @shaun-edwards to merge or wait.

**Comment by gomezc** [comment]
sounds good to me

**Comment by MauleshSTrivedi** [comment]
>  believe @MauleshSTrivedi is working on getting that fixed in his next pull request. 

yup, I will be getting back on this as soon as possible.

**Pull request merged**
