### PR TITLE
Added customToolFrameTF() function to address Issue #20.

### PR DESCRIPTION
**Pull request by MauleshSTrivedi**
Added support for custom tool frame to solve IK.

### CODE REVIEW

**Comment by nsnitish** [comment]
@MauleshSTrivedi ! I think you have uploaded some cmake and catkin generated files which should not be here. Please get rid of those. Also, the travis is failing.

**Comment by MauleshSTrivedi** [comment]
@nsnitish Oh, my bad, I didn't realize. I'll get on it in a bit. I will update this PR by tomorrow morning.

**Comment by shaun-edwards** [comment]
@MauleshSTrivedi, always review the PR changes before you submit.  Mistakes such as this are obvious in the changes tab.

**Comment by gavanderhoorn** [comment]
@MauleshSTrivedi: out of curiosity: how did you setup your workspace? Seeing those CMake configuration phase files in your PR makes me wonder if you are using the `moveit_simple` package root as the root of your workspace.

How are you building things?

**Comment by MauleshSTrivedi** [comment]
@gavanderhoorn I think these files crept in when I tried to sync my project with QT (as far as I can remember).. my project setup looks something like this -- /home/mauleshtrivedi/foo_projects/moveit_simple_workspace/src/moveit_simple
/home/mauleshtrivedi/foo_projects/moveit_simple_workspace/src/prettyprint

And the only git repositories in my foo_projects are moveit_simple and prettyprint. Does that help?

**Comment by gavanderhoorn** [comment]
qtc will do that to you, yes.

Have you looked at @levi-armstrong's plugin?

**Comment by MauleshSTrivedi** [comment]
@gavanderhoorn I have not  looked into it but that's a good idea.. let me try that later with another test project.. for now, I need to find a way to remove these autogenerated files.. I'm thinking of just creating a fresh repo in the worst case.. shouldn't take time.

**Comment by gavanderhoorn** [comment]
Commit / stash any outstanding changes, make sure you don't have any untracked files that should really be tracked, then run a `git clean -fnd` and inspect the output.

If it's ok, run `git clean -fd` and your clones should be back to their `HEAD`.

**Comment by MauleshSTrivedi** [comment]
@gavanderhoorn git clean returns:
Would remove moveit_simple/CMakeFiles/CMakeTmp/
Would remove moveit_simple/gtest/
Would remove moveit_simple/test_results/

But there are more than these 3 directories that QT created.. I'll remove these from my commit for now, but I still think it would be a better idea to clone moveit_simple from scratch just to be sure (I might be overthinking)

**Comment by gavanderhoorn** [comment]
Up to you.

**Comment by MauleshSTrivedi** [comment]
@shaun-edwards So sorry for the mess.. I should've been more careful before submitting the PR. I'll make sure to double check travis before submitting a request.

**Comment by MauleshSTrivedi** [comment]
@gavanderhoorn Thank you so much. You have been most helpful. I've installed Levi's ppa and I'll test it with qt in a bit.

**Comment by shaun-edwards** [comment]
+1 to using Levi's QT plugin

**Pull request closed without merging**
