### PR TITLE
Split moveit_simple.cpp into Multiple Files

### PR DESCRIPTION
**Pull request by geoffreychiou**
I split moveit_simple into multiple files instead of keeping everything in a single file to make things more maintainable. There should be no functionality changes.

@joshuaplusone please review.

### CODE REVIEW

**Review by joshuaplusone — APPROVED** [review]

**Comment by shaun-edwards** [comment]
CI Failed :(

**Comment by geoffreychiou** [comment]
> CI Failed :(

Agh this doesn't make sense, passing here: https://travis-ci.org/geoffreychiou/moveit_simple

Going to try and figure out why...

**Comment by geoffreychiou** [comment]
Looks like its passing now after restart.

**Comment by geoffreychiou** [comment]
Merging for now, i'll look into why it sometimes fails at a later date.

**Pull request merged**
