### PR TITLE
moveit_simple motoman_mh5 wrapper

### PR DESCRIPTION
**Pull request by MauleshSTrivedi**
Integrated the moveit_simple upgrades from @shaun-edwards /moveit_simple indigo-branch with the motoman_mh5 robot. The updates include functionalities for adding custom tool onto the motoman as well as the capability to dynamically reconfigure trajectory execution speed.

### CODE REVIEW

**Comment by MauleshSTrivedi** [comment]
TODO: Modify/Add some more tests for Interpolation and Singularity.

**Comment by MauleshSTrivedi** [comment]
@shaun-edwards Could you please review this PR when you get time. I've updated it so that it has the changes from Issue #8, Issue #17 and Issue #20. It also includes the modifications made by @gavanderhoorn from day before. Thanks.

**Comment by shaun-edwards** [comment]
@MauleshSTrivedi, did you delete the Kuka completely?  I thought you would keep both.

**Comment by MauleshSTrivedi** [comment]
@shaun-edwards I had separated out the branches and planned to organize the directories before adding them under the same moveit_simple root.. I've separated the Tests under different sub-directories.. we can clean up/organize them later on. Thanks.

**Comment by MauleshSTrivedi** [comment]
@shaun-edwards we are good to go!

**Comment by MauleshSTrivedi** [comment]
Moving this to #47

**Pull request closed without merging**
